### ISSUE TITLE
Limit by library

### ISSUE THREAD

**Issue by JamesMarcum** [alexjmck/BooksAPI-Komga#5]
I have several libraries, all quite large.  Two are manga, others are comics, novels, etc.  I want to be able to limit it to only scan one library when I run it.

**Describe the solution you'd like**
Either a library selection list, or a setting in the config.py that would allow library limiting.

**Comment by JamesMarcum** [comment]
Found a workaround - create regular user, limit libraries, then make admin.  Can only see those libraries.

**Comment by alexjmck** [comment]
sounds good
